/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "led.h"
#include "switch.h"
#include "iwdg.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	LedInit(LED_RED_PIN);
	if(IsIWDGReset()) {
		while(1) {
			LedBlink(LED_RED_PIN, 200);
			DelayMs(200);
		}
	}
	SwitchInit(SWITCH_PIN);
	LedInit(LED_GREEN_PIN);
	IWDGInit(5000);
	while(1) {
		// following task (switch+led) must be completed in 5000 ms; otherwise reset
		// wait until switch is pressed
		while(SwitchGetState(SWITCH_PIN) == 0)
			;
		// blink led
		LedBlink(LED_GREEN_PIN, 500);
		// refresh iwdg
		IWDGRefresh();
	}
	return 0;
}
